# -*- coding: utf-8 -*-
"""Session_4_Categorical_Column_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18Am-bOU8GCFrbPDDdiNA1ui7vr4V5uF-
"""

# import the packages
# read the data
# divide into cat num coumns

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='Visadataset.csv'
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

num

"""**prevailing_wage**

- len

- max

- min

- mean

- median

- 25percentile

- 50 percentile

- 75p
"""

wage_data=visa_df['prevailing_wage']
len(wage_data)

min(wage_data)

wage_data.min()

np.min(wage_data)

wage_data=visa_df['prevailing_wage']
min(wage_data),wage_data.min(),np.min(wage_data)

max(wage_data),wage_data.max(),np.max(wage_data)

wage_data.mean(),np.mean(wage_data)

wage_data.median(),np.median(wage_data)

"""**qunatile-percentile**"""

p_25=np.percentile(wage_data,25)
p_25

p_50=np.percentile(wage_data,50)
p_50

p_75=np.percentile(wage_data,75)
p_75

q_25=np.quantile(wage_data,0.25)
q_50=np.quantile(wage_data,0.50)
q_75=np.quantile(wage_data,0.75)

np.quantile(wage_data,0.25)

wage_data=visa_df['prevailing_wage']
wage_count=len(wage_data)
wage_min=round(wage_data.min(),2)
wage_mean=round(wage_data.mean(),2)
wage_med=round(wage_data.median(),2)
wage_25p=round(np.percentile(wage_data,25))
wage_50p=round(np.percentile(wage_data,50))
wage_75p=round(np.percentile(wage_data,75))
wage_max=round(wage_data.max(),2)
l=[wage_count,wage_min,wage_mean,wage_med,
   wage_25p,wage_50p,wage_75p,wage_max]
Id=['Count','Min','Mean','Median','25p','50p',
     '75p','Max']

pd.DataFrame(l,columns=['prevailing_wage'],index=Id)
#pd.DataFrame(l,Id,['prevailing_wage'])

L=[]
for i in num:
    data=visa_df[i]
    count=len(data)
    Min=round(data.min(),2)
    mean=round(data.mean(),2)
    med=round(data.median(),2)
    p_25=round(np.percentile(data,25))
    p_50=round(np.percentile(data,50))
    p_75=round(np.percentile(data,75))
    Max=round(data.max(),2)
    l=[count,Min,mean,med,
       p_25,p_50,p_75,Max]
    L.append(l)
    Id=['Count','Min','Mean','Median','25p','50p',
         '75p','Max']

pd.DataFrame(L,columns=Id,index=num).T

visa_df.describe()

"""**percentile concept**

- 25p: 25percentage of data below 25p value

- wage_25p: 34015.48

    - there 25*(25480)/100=6370 applicants have salary less tha 34015

- wage_50p: 70308.12

    - there 50*(25480)/100=12740 applicants have salary less tha 70308.12

- wage_75p: 107735.51

    - there 75*(25480)/100=19110 applicants have salary less tha 107735.51

"""

con=visa_df['prevailing_wage']<wage_25p
len(visa_df[con]),len(visa_df)*25/100
len(visa_df[con])==len(visa_df)*25/100

len(visa_df)*25/100

# **Emperical rule**

# u-1*sigma  to  u+1*sigma 68%

# step-1: wage data mean (u)
# step-2: wage data std (sigma)
# step-3: LB=u-1*sigma
# step-4: UB=u+1*sigma
# step-5: con1=visa_df['prevailing_wage']>LB
# step-6: con2=visa_df['prevailing_wage']<UB
# step-7: con=con1 & con2
# step-8: len(visa_df[con])

wage_data=visa_df['prevailing_wage']
U=wage_data.mean()
sigma=wage_data.std()
LB=U-1*sigma
UB=U+1*sigma
con1=visa_df['prevailing_wage']>LB
con2=visa_df['prevailing_wage']<UB
con=con1 & con2
len(visa_df[con])==68*25480/100

"""**Conclusion**: Emperical rule failed wage data does not following Normal distribution

**Histogram**
"""

plt.hist(wage_data,bins=40)

inter_count,inter_vals,n=plt.hist(wage_data,bins=10)

inter_count

inter_vals

2.13670000e+00, 3.19229500e+04,

3.19229500e+04

wage_data=visa_df['prevailing_wage']
lb=2.13670000e+00
ub=3.19229500e+04
con1=wage_data>=lb
con2=wage_data<ub
con=con1 & con2
len(visa_df[con])

"""**Outlier analysis**

- we understood emperical rule failed

- Then we plotted histogram its slightly deviated

- So it indicates the data has outliers

- Outliers can be show by **box plot**



           Q1-1.5IQR   Q1   median  Q3   Q3+1.5IQR
                       |-----:-----|
       o      |--------|     :     |--------|    o  o
                       |-----:-----|
       flier                                  fliers
                            IQR

$box plot$
"""

wage_data=visa_df['prevailing_wage']
plt.boxplot(wage_data,vert=False)
plt.show()

plt.figure(figsize=(8,4))
plt.subplot(1,2,1).hist(wage_data)
plt.subplot(1,2,2).boxplot(wage_data,vert=False)
plt.show()

"""**outliers data**"""

# q1
# q2
# q3
# IQR=q3-q1
# UB=q3+1.5*IQR
# LB=q3-1.5*IQR
# con1= wage >UB
# con2= wage<LB
# con= con1 | con2  outliers

# con1= wage<UB
# con2= wage > LB
# con3= con1 & con2

q1=np.percentile(wage_data,25)
q2=np.percentile(wage_data,50)
q3=np.percentile(wage_data,75)
IQR=q3-q1
UB=q3+1.5*IQR
LB=q1-1.5*IQR
con1= wage_data >UB
con2= wage_data<LB
con= con1 | con2
outliers_df=visa_df[con]
len(outliers_df)

outliers_df

q1=np.percentile(wage_data,25)
q2=np.percentile(wage_data,50)
q3=np.percentile(wage_data,75)
IQR=q3-q1
UB=q3+1.5*IQR
LB=q1-1.5*IQR
con1= wage_data<UB
con2= wage_data>LB
con= con1 & con2
non_outliers_df=visa_df[con]
len(non_outliers_df)

25053+427==25480

"""**fill the outliers**

- drop the outliers

- fill with median

- winsorization: fill with LB and UB
"""

# Fill the outliers using median
outliers_df
outliers_df['prevailing_wage']
outliers_df['prevailing_wage'].values
outliers=outliers_df['prevailing_wage'].values.tolist()
l=[]
wage_data=visa_df['prevailing_wage']
wage_med=wage_data.median()
for value in wage_data:
    if value in outliers:
        l.append(wage_med)
    else:
        l.append(value)
visa_df['prevailing_wage1']=l
visa_df

plt.figure(figsize=(8,4))
plt.subplot(1,2,1).hist(visa_df['prevailing_wage1'])
plt.subplot(1,2,2).boxplot(visa_df['prevailing_wage1'],vert=False)
plt.show()

plt.figure(figsize=(8,4))
plt.subplot(2,2,1).hist(visa_df['prevailing_wage1'])
plt.subplot(2,2,2).boxplot(visa_df['prevailing_wage1'],vert=False)
plt.subplot(2,2,3).hist(wage_data)
plt.subplot(2,2,4).boxplot(wage_data,vert=False)
plt.show()

wage_data=visa_df['prevailing_wage']
q1=np.percentile(wage_data,25)
q2=np.percentile(wage_data,50)
q3=np.percentile(wage_data,75)
IQR=q3-q1
UB=q3+1.5*IQR
LB=q1-1.5*IQR
visa_df['prevailing_wage2']=wage_data.clip(lower=LB,upper=UB)
visa_df

plt.figure(figsize=(8,4))
plt.subplot(2,2,1).hist(visa_df['prevailing_wage2'])
plt.subplot(2,2,2).boxplot(visa_df['prevailing_wage2'],vert=False)
plt.subplot(2,2,3).hist(wage_data)
plt.subplot(2,2,4).boxplot(wage_data,vert=False)
plt.show()

