# -*- coding: utf-8 -*-
"""Session_3_Multiple_column_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QuG8IKb06g-ZwJPkvDTd9C8k2fYl61ba
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='Visadataset.csv'
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

"""**frequeny table**"""

keys=visa_df['continent'].value_counts().keys()
values=visa_df['continent'].value_counts().values
df=pd.DataFrame(zip(keys,value),
            columns=['Label','No of applicants'])
df.to_csv('continent.csv',index=False)

"""**idea**

- I want to create all frequency tables

- and save in a new folder

- The folder is available in python current file location

- All steps automate

**step-1: create a folder using python code**
"""

import os
try:
    os.makedirs('frequeny_table')
except Exception as e:
    print(e)

os.makedirs('frequeny_table1',exist_ok=True)

keys=visa_df['continent'].value_counts().keys()
values=visa_df['continent'].value_counts().values
df=pd.DataFrame(zip(keys,values),
            columns=['Label','No of applicants'])
# Absolute path
path=r'C:\Users\omkar\OneDrive\Documents\Data science\Naresh IT\Naresh IT\Data science\Batches\Batch_16_July\EDA\frequeny_table\continent.csv'
df.to_csv(path,index=False)

# Realtive path
path=r'.\frequeny_table\continent1.csv'
df.to_csv(path,index=False)

cwd=os.getcwd() # EDA
folder_name='frequeny_table'
new_dir=os.path.join(cwd,folder_name)
filename='continent2.csv'
path=os.path.join(new_dir,filename)
df.to_csv(path,index=False)

cat  # dont consider case_id
cat[1:]

visa_df['case_id'].nunique()

# step-1:
keys=visa_df['continent'].value_counts().keys()
values=visa_df['continent'].value_counts().values
df=pd.DataFrame(zip(keys,value),
            columns=['Label','No of applicants'])
# step-2
folder_name='frequeny_table'
os.makedirs(folder_name,exist_ok=True)

# step-3:
cwd=os.getcwd()
new_dir=os.path.join(cwd,folder_name)
file_name='continent.csv'
path=os.path.join(new_dir,file_name)

# step-4:
df.to_csv(path,index=False)

# step-1:
for i in cat[1:]:
    keys=visa_df[i].value_counts().keys()
    values=visa_df[i].value_counts().values
    df=pd.DataFrame(zip(keys,values),
                columns=['Label','No of applicants'])
    # step-2
    folder_name='frequeny_table'
    os.makedirs(folder_name,exist_ok=True)

    # step-3:
    cwd=os.getcwd()
    new_dir=os.path.join(cwd,folder_name)
    file_name=f'{i}.csv'
    path=os.path.join(new_dir,file_name)

    # step-4:
    df.to_csv(path,index=False)

"""**bar chart automate**"""

keys=visa_df['continent'].value_counts().keys()
values=visa_df['continent'].value_counts().values
plt.figure(figsize=(10,4))
plt.bar(keys,value)
plt.xlabel('labels')
plt.ylabel('count')
plt.title('continet_barchart')
plt.savefig('contienent_bar.jpg')

# step-1:
for i in cat[1:]:  # misrake cat:
    keys=visa_df[i].value_counts().keys()
    values=visa_df[i].value_counts().values
    plt.figure(figsize=(10,3))
    plt.bar(keys,values)
    # step-2
    folder_name='Bar_charts'
    os.makedirs(folder_name,exist_ok=True)

    # step-3:
    cwd=os.getcwd()
    new_dir=os.path.join(cwd,folder_name)
    file_name=f'{i}.jpg'
    path=os.path.join(new_dir,file_name)

    # step-4:
    plt.savefig(path)

# step-1:
for i in cat[1:]:  # misrake cat:
    keys=visa_df[i].value_counts().keys()
    values=visa_df[i].value_counts().values
    plt.pie(values,
            explode=[0.1 for i in range(len(keys))]
            labels=keys)
    # step-2
    folder_name='pie_charts'
    os.makedirs(folder_name,exist_ok=True)

    # step-3:
    cwd=os.getcwd()
    new_dir=os.path.join(cwd,folder_name)
    file_name=f'{i}.jpg'
    path=os.path.join(new_dir,file_name)

    # step-4:
    plt.savefig(path)