# -*- coding: utf-8 -*-
"""Session_6_Encoding.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PUsubIKpXC4_z_BpsU8-8L7lqAS89huB

- Generally ML models Developed by maths

- Convert categorical column to Numerical columns

- Here we are transform the data

- This method is called as **Encoding**

- Feature Analaysis :  first 5 sesssions

- Feature Engineering : Transform the data

- Feature selection : Machine learning

- Before Model Development

- We will do EDA : Exploratry data analysis

    - Features(Columns) analysis

        - Categorical , Numerical , Outlier analysis, Bivariate, Multivariate

        - We will get the insights

    - Feature Engineering

        - we will modify the data

        - Models developed by maths

        - Encoding : Convert categorical data to Numerical Variables

        - Scaling :  All the numerical columns makes under one scale

        - Transformations :  All the maths developed by assumption data follows Normal distribution

            - Convert skewed distribution to Normal

    - Feature selection

- map

- LabelEncoder

- OneHotEncoder
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

path='Visadataset.csv'
visa_df=pd.read_csv(path)
cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

# check how many unique values available
visa_df['case_status'].unique()

# create a dictionary assigin a number start with zero
# for each lables based on alphabetical order
d={'Certified':0,'Denied':1}
d

# map the dictionary with column
visa_df['case_status']=visa_df['case_status'].map(d)

visa_df

path='Visadataset.csv'
visa_df=pd.read_csv(path)

visa_df['case_status'].unique()
d={'Certified':0,'Denied':1}
visa_df['case_status']=visa_df['case_status'].map(d)

labels=sorted(visa_df['continent'].unique())
# d={}
# for i in range(len(labels)):
#     key=labels[i]
#     d[key]=i
d={labels[i]:i for i in range(len(labels))}  # i labels[i]
d

path='Visadataset.csv'
visa_df=pd.read_csv(path)

labels=sorted(visa_df['continent'].unique())
d={labels[i]:i for i in range(len(labels))}  # i labels[i]
visa_df['continent']=visa_df['continent'].map(d)
visa_df

path='Visadataset.csv'
visa_df=pd.read_csv(path)

cat=visa_df.select_dtypes(include='object').columns
for i in cat:
    labels=sorted(visa_df[i].unique())
    d={labels[i]:i for i in range(len(labels))}  # i labels[i]
    visa_df[i]=visa_df[i].map(d)
visa_df

"""**LabelEncoder**

- package name: **sklearn**

    - class: **preprocessing**

        - method: **LabelEncoder**

- from sklearn.preprocessing import LabelEncoder
"""

- step-1: import the method

- step-2: save the method

- step-3: apply fit transform

**fit transform**

- fit: finding something

    - first we are finding dictionary

- transform: change the data

    - using the dictionary we are changing Eng to Number

from sklearn.preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)

le=LabelEncoder()
visa_df['case_status']=le.fit_transform(visa_df['case_status'])

from sklearn.preprocessing import LabelEncoder
path='Visadataset.csv'
visa_df=pd.read_csv(path)
le=LabelEncoder()
for i in cat:
    visa_df[i]=le.fit_transform(visa_df[i])

visa_df

"""**OneHotEncoder**

- The method name is: pd.get_dummies

|case_status|case_status_Denied|case_staus_Certified|
|-|-|-|
|Denied|1|0|
|Certified|0|1|
"""

# continent  Continet_asia   continent_africa  continet_Europe
# asia          1               0                 0
# africa        0               1                 0
# Europe        0               0                 1

path='Visadataset.csv'
visa_df=pd.read_csv(path)

pd.get_dummies(visa_df['continent'],
              dtype='int')

visa_df
visa_df['continent']
visa_df['continent'].values

