# -*- coding: utf-8 -*-
"""Session_2_Categorical_Data_Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18d-GMrMiihO7xVT3vIfDd6L7viawkEmd

**Step-1:Import Packages**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Step-2: Read the data**"""

path='Visadataset.csv'
visa_df=pd.read_csv(path)
visa_df

path='bank.csv'
bank_df=pd.read_csv(path,sep=';')
bank_df

"""**Step-3:DATA qucik checks Visadf**

- columns

- shape

- dtype

- len

- head

- tail

- info

- isnull
"""

visa_df.columns

visa_df.shape
print('The number of rows are:',visa_df.shape[0])
print('The number of columns are:',visa_df.shape[1])

visa_df.dtypes

types=visa_df.dtypes
types

"""**Method-1**"""

type_df=pd.DataFrame(types).reset_index()
print(type_df.columns) # 2
type_df.columns=['Column Name','Data type']
type_df

types

# types is a series it has both keys and values
types.keys()

types.values

dir(types)

# step-1:
types=visa_df.dtypes
# step-2:
keys=types.keys().tolist()
# list(types.keys())
# step-3:
values=types.values.tolist()
# when we have two lists are avaialble
type_df=pd.DataFrame(zip(keys,values),
            columns=['Column','Type'])
type_df.to_csv('Datatype.csv',index=False)

keys,values

cat=[]
num=[]
for i,j in zip(keys,values):
    if j=='object':
        cat.append(i)
    else:
        num.append(i)

cat

num

"""**Select_dtypes**"""

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

"""**Task-2:**

- I want to how many memebrs are available in continent
"""

# step-1: Main dataframe
visa_df
# step-2: select continent column
visa_df['continent']
# step-3: apply condition
con=visa_df['continent']=='Asia'
# step-4: extract the True values
len(visa_df[con])

con=visa_df['continent']=='Asia'
len(visa_df[con])
###########################################
con=visa_df['continent']=='Africa'
len(visa_df[con])

"""**unique**"""

visa_df['continent'].unique()

"""**nunique**"""

visa_df['continent'].nunique()

con=visa_df['continent']=='Asia'
len(visa_df[con])
###########################################
con=visa_df['continent']=='Africa'
len(visa_df[con])
#############################################
con=visa_df['continent']=='North America'
len(visa_df[con])
con=visa_df['continent']=='Europe'
len(visa_df[con])
con=visa_df['continent']=='South America'
len(visa_df[con])
con=visa_df['continent']=='Oceania'
len(visa_df[con])

con=visa_df['continent']==i
len(visa_df[con])

labels=visa_df['continent'].unique()
for i in labels:
    con=visa_df['continent']==i
    count=len(visa_df[con])
    print(count)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


path='Visadataset.csv'
visa_df=pd.read_csv(path)
visa_df

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

"""**raw data**"""

visa_df # df
visa_df['continent'] # series
visa_df['continent'].values # array of values

"""**frequency tabel**"""

con=visa_df['continent']=='Asia'
len(visa_df[con])

visa_df['continent'].unique()

labels=visa_df['continent'].unique()
count=[]
for i in labels:
    con=visa_df['continent']==i
    count.append(len(visa_df[con]))
count

# we have two lists
# one list name: labels
# count
# if you are not able to do this
# katam zindagi ==== 1week
continent_df=pd.DataFrame(zip(labels,count),columns=['Continent','No Of Applicants'])

# all together
path='Visadataset.csv'
visa_df=pd.read_csv(path)
visa_df

cat=visa_df.select_dtypes(include='object').columns
num=visa_df.select_dtypes(exclude='object').columns

labels=visa_df['continent'].unique()
count=[]
for i in labels:
    con=visa_df['continent']==i
    count.append(len(visa_df[con]))
count

continent_df=pd.DataFrame(zip(labels,count),
                          columns=['Continent','No Of Applicants'])

continent_df.to_csv('continent_df.csv',index=False)

continent_df

"""**value_counts**"""



visa_df['continent'].value_counts()

"""**Group by**"""

# dividing continents into a group
# then calculate size of each group
visa_df.groupby('continent').size()

continent_keys=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
continent_df=pd.DataFrame(zip(continent_keys,continent_values),
            columns=['Continent','No Of Applicants'])
continent_df

"""**Bar chart**

- under matplotlib

- plt.bar
"""

continent_keys=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
col=['pink','yellow','red','green','orange','violet']
plt.figure(figsize=(10,4))
plt.bar(continent_keys,
       continent_values,
       color=col)
plt.xlabel('Continent')
plt.ylabel('No of Applicants')
plt.title('Contienent_bar')
plt.savefig('Contienent_bar.jpg')
plt.savefig('Contienent_bar.png')
plt.show()

"""**Relative frequency**"""

visa_df['continent'].value_counts(normalize=True)*100

"""**pie**"""

continent_keys=visa_df['continent'].value_counts().keys()
continent_values=visa_df['continent'].value_counts().values
plt.pie(continent_values,
        explode=[0.1,0.1,0.1,0.1,0.1,0.1],
        labels=continent_keys,
       autopct="%0.2f%%",
       startangle=45,
       radius=2)

plt.show()

