# -*- coding: utf-8 -*-
"""Session_1_Basic_Data_Frame_operations.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y7r6MCAwODwGF5410tQwLFnwHDwju2Ut
"""

==================== Data Analysis =============================
1. Pandas         :  Data frame analysis
2. Numpy          :  Numerical analysis
3. matplotlib     :  Graphs and plots
4. seaborn        :  plots
5. Bokhe         :   plots
6. plotly         :  plots

=================== Machine Learning ============================
7. stats          : for statistical models
8. scikit-learn(sklearn) :  ML models

===================  Deep learning ============================
9. opencv         : Computer vision
10. pillow        : Image operations
11. tensorflow    : Neural Network creations (developed by google)
12. keras         : NN
13. pytorch       : alternative package of tensorflow (facebook meta)

==================== NLP ========================================
14. NLTK          : Natural language toolkit
15. SpaCy         : Alternative to NLTK
16. wordcloud     : most frequent occured words

======================= Scarapping =================================
17. SqLite        : Data base creation
18. Beautiful soup
19. Selenium

======================== API creations ===========================
20. Flask
21. FastAPI
22. Gradio
23. Django
======================= UI app creation =========================
24.Streamlit

===================== Transfer learning models(DL) ===========
25. Mobilenet
26. Resnet
27. VGGnet
28. Inception
29. Yolo    :  Ultralytics

===================== Transfer learning models(NLP) ===========
30. Word2vec
31. GloVe

======================== Huging Face Transformers ===============
32. BERT   : Bi Directional Encoder representation of Transformers

========================== Allen NLP =======================
33. Allen NLP packages

================== GenAI =============================
34. LangChain
35. Google GeminiAi realted pcakges
36. OpenAI GPT realted packages
37. Amazon BedRock realted packages
38. Meta Llama  related packages

==================== Image and Video Generations ==============
39. GAN models realted packages
40. SORA related packages

=================== Model deployment (MlOps)===================
41. mlflow using databricks
42. kubeflow (GCP account)

==================== Cloud applications =====================
43. Azure ML realted packages
44. GCP VertexAI related packages
45. AWS Sagemaker realted packages

==================== small ===================================
46. time
47. logging
48. math
49. random
50. env
51. os

"""**Step-1: Import packages**"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

"""**Step-2: create a Dataframe using list**

- data : your data either list or dict

- index : we need to provide a list

- columns : we need to provide a list

"""

names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
             columns=['Names'])
# pd.DataFrame(data,index,columns)

"""**Step-3: change the index**"""

names=['Ramesh','Suresh','Satish']
pd.DataFrame(names,
             index=['A','B','C'],
             columns=['Names'])

names=['Ramesh','Suresh','Satish']
idx=['A','B','C']
cols=['Names']
pd.DataFrame(names,
             index=idx,
             columns=cols)

"""**Step-4: Add multiple columns**"""

names=['Ramesh','Suresh','Satish']
age=[20,22,24]
pd.DataFrame(zip(names,age),
            columns=['Names','Age'])

"""**Step-5: Create empty dataframe and update the columns**"""

df=pd.DataFrame()
df['Names']=['Ramesh','Suresh','Satish']
df['Age']=[20,22,24]
df

"""**Step-6: Add a new column with existing dataframe**"""

names=['Ramesh','Suresh','Satish']
age=[20,22,24]
df=pd.DataFrame(zip(names,age),
            columns=['Names','Age'])
df['City']=['Hyd','Pune','Blr']
df

"""**Step-7: overwrite the column values**

- I want to overwrite my age values

- originally age is = [20,22,24]

- now i want to update the age = [30,32,34]
"""

df['Age']=[30,32,34]
df['age']=[30,32,34]
df

"""**Step-8:Drop the column**

- labels

- axis

- index

- columns

- inplace
"""

df

df.drop('age')   # error
df.drop('age',axis=0) # error
df.drop('age',axis=1) # correct
# here python assume age is a label
# python ask qn : is it index label or column label
# axis=1 means for columns
# axis=0 means for rows
# by default axis=0

df.drop('age',
        axis=1)

df # we are able to see old column
# becuase we did not apply inplace=True

# whenever we use columns label
# no need of axis
df.drop(columns=['age'],
        inplace=True)

df

# drop index= 2
df.drop(2,
        axis=0)

df.drop(index=2)

"""**Step-9:rename the column**"""

mapper: dictionary {'City':'city'}
index:
columns: {'City'}
axis:
inplace:

df
# I want to change City column: city

dict1={'City':'city'}
df.rename(dict1)

dict1={'City':'city'}
df.rename(dict1,axis=1)

dict1={'City':'city'}
df.rename(columns=dict1)

df

dict1={'City':'city'}
df.rename(columns=dict1,
         inplace=True)
df

# can you change 2 to 'B'
# sir whats the difference between labels and index sir?
# index 0,1,2
# columms Names, Age,city
# label : Names  0

dict1={2:'B'}
df.rename(dict1,axis=0)

dict1={2:'B'}
df.rename(index=dict1)

df1=pd.DataFrame()
df1['value']=[i for i in range(1,10)]
df1['square_value']=[i**2 for i in range(1,10)]
df1['cube_value']=[i**3 for i in range(1,10)]
df1

"""- len

- columns

- shape

- dtypes

- head

- tail
"""

df1.columns

list(df1.columns)

df1.columns.to_list()

df1.shape
# 9 rows and 3 columns

df1.dtypes
# integer we will get integer
# float we will get float
# string we will get object

df.dtypes

df1.head(2)

df1.tail()

len(df1)

df1.isnull()
# we are asking a qn
# a null value availbel or not
# True or False
# True means yes NULL available
# False means No NULL value not available

df1.isnull().sum()
# column wise null value count will display

df1.info()

"""**Step-10**

- How to change a specific value of a column

- df1.drop

    - either it will drop column or index

- df1.rename

    - either it will rename column or index

- df1.replace
"""

df1
# replace cube_vlaue 64 to 464

df1.replace(64,464) # all the data will replace
df1.replace({64:464,1:111}) # all the data will replace

"""**Step-11: Selection of a column**"""

df1['cube_value']
# series
# series looks like dataframe
# rows and columns

type(df1)

type(df1['cube_value'])

df1.shape # 2D

df1['cube_value'].shape
# 1D data

df1[['cube_value']]

type(df1[['cube_value']])
df1[['cube_value']].shape

# square_value
# cube_value
# multiple always keep those in list
df1[['cube_value','square_value']]

df1['cube_value'].replace(64,464,inplace=True)

df1

"""**Step-12:How to append a row**

- loc

- iloc
"""

# df1.loc[rows,columns]
# df1.iloc[rows,columns]

# we can select particular rows and columns using a list: [start:stop:step]

df1.iloc[3:7,1:3]
df1.loc[3:7,['square_value','cube_value']]
cols=['square_value','cube_value']
df1.loc[3:7,cols]

df1.iloc[[2,3,4]] #
df1.iloc[[2]]
df1.iloc[2]
df1.iloc[[2,3,4],[0,2]]
df1.iloc[2,0]
df1.iloc[:,0]
df1.iloc[2,:]
df1.iloc[[2],:]
df1.iloc[2:6,0]
df1.iloc[2:6,[0]]

df1.iloc[[2,3,4]]
# selecting 3 rows, all the columns
# dataframe

df1.iloc[[2]] # 2D df

df1.iloc[2]  # 1D series

df1.iloc[[2,3,4],[0,2]]
# 2,3,4 row
# 0 and 2nd index (1,3)

df1.iloc[2,0]

df1
# in column1 (value) i want to replace value to 60
# based on specific index
df1.iloc[5,0]

df1.iloc[:,0]
# rows and first column

df1.iloc[2,:]

df1

df1.iloc[[2],:]

df1.iloc[2:6,0]

df1.iloc[2:6,[0]]

"""**how to append a row**"""

df1

df1.loc[9]=[10,100,1000]

len(df1)

ID=len(df1)
df1.loc[ID]=[10,100,1000]
df1

"""**Step-13: Save the dataframe**

- we can save dataframes in two ways

- .csv

- .xlsx

- where I want to save : directory

- what the the filename to save: filename

- what is the type of a file : extension

- different folder : r"C:\Users\omkar\OneDrive\Documents\Gen_AI\data1.csv"

- different folder : r"C:\Users\omkar\OneDrive\Documents\Gen_AI\data1.xlsx"

- same folder: r"data1.csv"  or r"data1.xlsx"
"""

csv_path=r"C:\Users\omkar\OneDrive\Documents\Gen_AI\data1.csv"
excel_path=r"C:\Users\omkar\OneDrive\Documents\Gen_AI\data1.xlsx"
df1.to_csv(csv_path) # index column created extra
df1.to_excel(excel_path) # index column created extra

csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path) # index column created extra
df1.to_excel(excel_path) # index column created extra

"""**Step-14 read the data**"""

csv_path=r"data1.csv"
pd.read_csv(csv_path)

excel_path=r"data1.xlsx"
pd.read_excel(excel_path)

csv_path=r"data1.csv"
excel_path=r"data1.xlsx"
df1.to_csv(csv_path,index=False) # index column created extra
df1.to_excel(excel_path,index=False) # index column created extra

csv_path=r"data1.csv"
pd.read_csv(csv_path)

